In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [5]:
# делим ноль на ноль
arr / arr

C:\Users\ultra\AppData\Local\Temp\ipykernel_492\3258319771.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
zero = np.array(0)
zero

array(0)

In [9]:
# делим единицу на ноль и получаем бесконечность
1 / zero

C:\Users\ultra\AppData\Local\Temp\ipykernel_492\1419307174.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / zero


inf

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [12]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [13]:
# получим минус бесконечность
np.log(arr)

C:\Users\ultra\AppData\Local\Temp\ipykernel_492\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [14]:
# дисперсия и среднеквадратичное отклонение
print(f'Дисперсия равняется: {np.var(arr)}')
print(f'СКО равняется: {np.std(arr)}')

Дисперсия равняется: 10.0
СКО равняется: 3.1622776601683795


In [17]:
arr2d = np.arange(25).reshape((5, 5))
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
# строки исчезают и мы получаем результат сумирования по каждой колонки
# УКАЗЫВАЕМ ТУ ОСЬ, КОТОРАЯ ДОЛЖНА ИСЧЕЗНУТЬ ПРИ СУММИРОВАНИИ
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [19]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])