In [1]:
import numpy as np

In [2]:
mylist = (1, 2, 3)

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
myarr = np.array(mylist)

In [5]:
myarr

array([1, 2, 3])

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6,], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
# создадим массив из нулей
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# создадим массив из единиц
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# создадим равномерно распределенные числа в течение заданного интервала
np.linspace(0, 18, 4)

array([ 0.,  6., 12., 18.])

In [22]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

# [numpy.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [24]:
# создаём единичную матрицу
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# получим массив из случайное равномерного распределения между [0, 1)
np.random.rand(2, 3)

array([[0.49838241, 0.75626083, 0.78930757],
       [0.5505798 , 0.77031807, 0.23072336]])

# [numpy.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

In [37]:
# нормальное распределение (Гаусса). При стандартизации
# математическое ожидание = 0, а дисперсия = 1
np.random.randn(10)

array([ 1.06527903, -0.98521881, -1.96333359,  0.04485738,  0.08173825,
       -1.51803317, -1.3092236 ,  1.22158198, -0.38428288,  1.1814344 ])

# [numpy.random.randn](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [38]:
# получим случайное целое число из нормального стандартного
# распределения заданых чисел, не включая последнее
# 3й аргумент отвечает за количество чисел
np.random.randint(0, 101, 5)

array([78, 66, 44, 23, 40])

In [39]:
np.random.randint(0, 10, (5, 3))

array([[9, 0, 8],
       [4, 2, 5],
       [5, 2, 6],
       [2, 7, 8],
       [3, 3, 7]])

# [numpy.random.randint](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)

In [47]:
# здесь случайный набор из 4х чисел меняться не будет
# для многократного повторения случайного эксперимента
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [62]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
# меняем форму массива и все числа должны поместиться точно
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
rand_arr = np.random.randint(0, 101, 10)
rand_arr

array([77, 86, 61, 39, 84, 79, 81, 52, 23, 25])

In [66]:
rand_arr.max()

86

In [67]:
# получим индекс минимального числа в массиве
rand_arr.argmin()

8

# [numpy.argmin](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html)

In [70]:
# атрибут для проверки типа массива
rand_arr.dtype

dtype('int32')

In [72]:
# посмотрим размер массива (атрибут)
arr.shape

(25,)

## Индексация и выбор данных из массива

In [80]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr[8]

8

In [82]:
arr[1:5]

array([1, 2, 3, 4])

In [83]:
arr[:5]

array([0, 1, 2, 3, 4])

In [84]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [86]:
# broadcasting - операция множественного присваивания
# изменения сохранятся!
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [89]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
# создаём не отдельный массив, а ссылки на существующий!
slice_of_array = arr[:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [91]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [96]:
# создаём явно новый массив
arr_copy = arr.copy()

In [97]:
arr_copy[:] = 100

In [98]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [99]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

# [numpy.ndarray.copy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html)

In [100]:
arr_2d = np.array([[5, 10, 15],
                   [20, 25, 30],
                   [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [101]:
arr_2d.shape

(3, 3)

In [102]:
arr_2d[0]

array([ 5, 10, 15])

In [103]:
arr_2d[2]

array([35, 40, 45])

In [104]:
print(arr_2d[1][1])
arr_2d[1, 1]

25


25

In [105]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [107]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
mask = arr > 4
mask

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [110]:
arr[mask]

array([ 5,  6,  7,  8,  9, 10])

In [111]:
# выбор по условию (conditional selection)
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

## операции numpy

In [113]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [115]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [116]:
# массивы должны быть одинаковых размеров!
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])